name: 申请友链
description: 填写希望链接的站点名和链接，添加一段自述，并上传头像
title: 友链申请
labels: 友链
body:
  - type: input
    id: name
    attributes:
      label: 站点名称
      placeholder: 如：石木古月的小窝
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: 站点链接
      placeholder: 个人网站、Github主页、Bilibili主页等任何可进行展示的网站皆可
    validations:
      required: true

  - type: input
    id: desc
    attributes:
      label: 个人介绍
      placeholder: 来点自述，给大家留下最好的第一印象
    validations:
      required: true

  - type: textarea
    id: avatar
    attributes:
      label: 展示头像
      placeholder: 在此处上传图片（要求长宽比为 1:1；格式支持 JPEG、PNG、GIF、BMP、WebP）
    validations:
      required: true
